name: CD - Deploy to Azure VM

on:
  push:
    branches:
      - test_branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}

          script: |
            git fetch origin
            git reset --hard origin/test_branch
            docker-compose up -d --build

